// 충동서버 크루 목록 (정적 데이터 - ID, 이름, 크루 정보)
export const CREW_LIST = [
  {
    name: "버컴퍼니",
    color: "#5B6AED",
    members: [
      { id: "devil0108",      name: "감스트",   leader: true },
      { id: "yeveee",         name: "유설아" },
      { id: "cctvno",         name: "유연서" },
      { id: "danchu17",       name: "단츄" },
      { id: "insome0319",     name: "따린" },
      { id: "gofl2237",       name: "해리" },
      { id: "qweasd3456",     name: "바밍" },
      { id: "honeys2",        name: "니니" },
      { id: "yjw5067",        name: "봄세이" },
      { id: "dnwnwjdqhr53",   name: "설레랑" },
      { id: "0e0e4e",         name: "키이세" },
      { id: "nmangoquince",   name: "망구랑" },
      { id: "alicehiyam",     name: "앨리스얌" },
      { id: "chachki",        name: "차쯔키" },
      { id: "42dadada",       name: "사이다" },
      { id: "yoonesaem",      name: "윤이샘" },
      { id: "yukki62",        name: "유키" },
      { id: "gio12025",       name: "류채아" },
    ],
  },
  {
    name: "홍신소",
    color: "#e74c3c",
    members: [
      { id: "lhtlgm",         name: "홍타쿠",   leader: true },
      { id: "zamgyeol",       name: "잠결" },
      { id: "guqlswls123",    name: "따스히" },
      { id: "rjsdnr115",      name: "고채린" },
      { id: "neul0908",       name: "모야" },
      { id: "015234",         name: "아눙" },
      { id: "jjoasseo13",     name: "죠아써" },
      { id: "layule",         name: "라율" },
      { id: "rlawlsthfw",     name: "힙비" },
      { id: "hibibi1",        name: "하비" },
      { id: "kkumong2222",    name: "또야몽" },
      { id: "villlo",         name: "왜냐니" },
      { id: "dlalswl8811",    name: "이깨굴" },
      { id: "hyundana",       name: "현단아" },
    ],
  },
  {
    name: "지력사무소",
    color: "#f39c12",
    members: [
      { id: "tjrdbs999",      name: "지피티",   leader: true },
      { id: "5959700",        name: "라무" },
      { id: "monas2",         name: "모나양" },
      { id: "singu64",        name: "싱유" },
      { id: "moolchoco",      name: "물초코" },
      { id: "niniming",       name: "니니밍" },
      { id: "kbs9981",        name: "김병살" },
      { id: "rkdmsdl782",     name: "한아련" },
      { id: "idlovehina",     name: "김쿼카" },
      { id: "xex3",           name: "목츄리" },
      { id: "meuuu3",         name: "메루" },
      { id: "asdf3845",       name: "나몽" },
      { id: "linco00",        name: "린코" },
    ],
  },
  {
    name: "습팸",
    color: "#3498db",
    members: [
      { id: "hwt1014",        name: "가습기",   leader: true },
      { id: "o0opha",         name: "서라0" },
      { id: "manlebreadtv",   name: "습늘빵" },
      { id: "gkxl1004",       name: "하티하티" },
      { id: "loveya4860",     name: "하루아이" },
      { id: "irrilll",        name: "이릴" },
      { id: "khj011219",      name: "기찬하" },
      { id: "janine95kim",    name: "재닌" },
      { id: "ju010228",       name: "쥬멩이" },
      { id: "jamyul2",        name: "잼율이" },
      { id: "pinkmold0317",   name: "강분팡" },
      { id: "ekrekrnfl9",     name: "야뿌" },
      { id: "odoeun",         name: "쨈도은" },
      { id: "tndk321",        name: "단수아" },
      { id: "ajvls609",       name: "이사호" },
      { id: "tpdusdl0218",    name: "뽀뽀" },
      { id: "kysvic2",        name: "체리즈" },
      { id: "tkfkdgodufks",   name: "소연화" },
      { id: "sinoost2",       name: "피너" },
    ],
  },
  {
    name: "꾸한성",
    color: "#9b59b6",
    members: [
      { id: "aksen7833",      name: "꾸티뉴",   leader: true },
      { id: "land4968",       name: "야무지" },
      { id: "northpole",      name: "엔쥬" },
      { id: "top6373",        name: "란다" },
      { id: "sellkey",        name: "셀키" },
      { id: "lika07",         name: "리카" },
      { id: "choelssu",       name: "철쑤" },
      { id: "koo2202",        name: "구본좌" },
      { id: "y0unggam",       name: "영감" },
      { id: "whiteone325",    name: "난워니" },
      { id: "not15987",       name: "다뮤" },
      { id: "dbsk0708",       name: "딴딴2당" },
      { id: "suupercutie",    name: "초귀요미" },
      { id: "mimmya0203",     name: "밈먀" },
      { id: "wooyah21",       name: "바먀" },
    ],
  },
  {
    name: "그린캠프",
    color: "#27ae60",
    members: [
      { id: "hrlim95",        name: "로기다",   leader: true },
      { id: "e9dongsung",     name: "추멘" },
      { id: "secymyong",      name: "묭씨" },
      { id: "fumagochi",      name: "푸마고치" },
      { id: "etwo22",         name: "이투" },
      { id: "angel000429",    name: "베지" },
      { id: "sakbi1",         name: "삭비" },
      { id: "wldms4482",      name: "비비" },
      { id: "eunchr",         name: "은초롱" },
      { id: "mnomno55",       name: "루디딕" },
      { id: "phs6162",        name: "찐랑" },
      { id: "miome3",         name: "고미호" },
      { id: "yotsubakoe",     name: "코에" },
      { id: "cosmicaaarrr",   name: "아르르" },
      { id: "imhanbily",      name: "한비" },
      { id: "oneon1y",        name: "온유일" },
    ],
  },
  {
    name: "털즈란",
    color: "#e67e22",
    members: [
      { id: "jaeparkk",       name: "박재박",   leader: true },
      { id: "nslah830",       name: "피치" },
      { id: "jo0ju492",       name: "에망" },
      { id: "morgan427",      name: "숙희" },
      { id: "ksue336",        name: "슈니" },
      { id: "hongkillsoon",   name: "홍길순" },
      { id: "leesoi34",       name: "냥쏘" },
      { id: "tdnlamuron",     name: "다시바" },
      { id: "yeyo25",         name: "예요예요" },
      { id: "hhr001234",      name: "어쩜냥이" },
      { id: "naye0418",       name: "나예" },
      { id: "ballty0719",     name: "공태연" },
    ],
  },
  {
    name: "버인협회",
    color: "#1abc9c",
    members: [
      { id: "cnsgkcnehd74",   name: "조경훈",   leader: true },
      { id: "bureu2002",      name: "부르" },
      { id: "ry0135",         name: "송소미" },
      { id: "pyowoo",         name: "표우" },
      { id: "sa5791",         name: "킹냥이" },
      { id: "kkyubog",        name: "뀨복" },
      { id: "hibby1004",      name: "너보링" },
      { id: "liloolil",       name: "해솔" },
      { id: "gjstn7637",      name: "아뚱" },
      { id: "dionzzz",        name: "하루비" },
      { id: "sie4yu",         name: "유시에" },
      { id: "nyanyavkr2",     name: "냐냐" },
      { id: "merryou",        name: "비숑" },
    ],
  },
  {
    name: "고래상사",
    color: "#2c3e50",
    members: [
      { id: "bach023",        name: "울산큰고래", leader: true },
      { id: "melodingding",   name: "멜로딩딩" },
      { id: "soyoung6056",    name: "빡쏘" },
      { id: "akdma9692",      name: "온자두" },
      { id: "nlov555jij",     name: "삐요코" },
      { id: "gyeonjahee",     name: "견자희" },
      { id: "gatgdf",         name: "쏭이" },
      { id: "joaras2",        name: "조아라" },
      { id: "doki0818",       name: "감자가비" },
      { id: "xpdpfv2",        name: "이지수" },
      { id: "ducke77",        name: "밀크티냠" },
      { id: "kimmaren77",     name: "김마렌" },
    ],
  },
];
