// 충동서버 크루 목록 (고정 멤버 - CSV 기준)
// 레벨/직업/무기 데이터는 Google Sheets에서 실시간 가져옴
const CREW_LIST = [
  {
    name: "버컴퍼니",
    color: "#5B6AED",
    members: [
      { id: "devil0108",      name: "감스트",   leader: true },
      { id: "yoonesaem",      name: "윤이샘" },
      { id: "honeys2",        name: "니니" },
      { id: "gio12025",       name: "류채아" },
      { id: "nmangoquince",   name: "망구랑" },
      { id: "gofl2237",       name: "해리" },
      { id: "danchu17",       name: "단츄" },
      { id: "insome0319",     name: "따린" },
      { id: "yeveee",         name: "유설아" },
      { id: "cctvno",         name: "유연서" },
      { id: "amaiyk0105",     name: "유키" },
      { id: "yjw5067",        name: "봄세이" },
    ],
  },
  {
    name: "지력사무소",
    color: "#f39c12",
    members: [
      { id: "tjrdbs999",      name: "지피티",   leader: true },
      { id: "5959700",        name: "라무" },
      { id: "quokka1228",     name: "김쿼카" },
      { id: "rkdmsdl782",     name: "한아련" },
      { id: "xex3",           name: "목츄리" },
      { id: "meuuu3",         name: "메루" },
      { id: "linco00",        name: "린코" },
      { id: "moolchoco",      name: "물초코" },
      { id: "asdf3845",       name: "나몽" },
      { id: "monas2",         name: "모나양" },
      { id: "singu64",        name: "싱유" },
      { id: "kbs9981",        name: "김병살" },
    ],
  },
  {
    name: "홍신소",
    color: "#e74c3c",
    members: [
      { id: "lhtlgm",         name: "홍타쿠",   leader: true },
      { id: "neul0908",       name: "모야" },
      { id: "zamgyeol",       name: "잠결" },
      { id: "rlawlsthfw",     name: "힙비" },
      { id: "hibibi1",        name: "하비" },
      { id: "guqlswls123",    name: "따스히" },
      { id: "kkumong2222",    name: "또야몽" },
      { id: "rjsdnr115",      name: "고채린" },
      { id: "hyundana",       name: "현단아" },
      { id: "villlo",         name: "왜냐니" },
      { id: "jjoasseo13",     name: "죠아써" },
      { id: "015234",         name: "아눙" },
    ],
  },
  {
    name: "버인협회",
    color: "#1abc9c",
    members: [
      { id: "cnsgkcnehd74",   name: "조경훈",   leader: true },
      { id: "liloolil",       name: "해솔" },
      { id: "bureu2002",      name: "부르" },
      { id: "sa5791",         name: "킹냥이" },
      { id: "pyowoo",         name: "표우" },
      { id: "merryou",        name: "비숑" },
      { id: "ry0135",         name: "송소미" },
      { id: "nyanyavkr2",     name: "냐냐" },
      { id: "sie4yu",         name: "유시에" },
      { id: "hibby1004",      name: "너보링" },
      { id: "dionzzz",        name: "하루비" },
      { id: "kkyubog",        name: "뀨복" },
    ],
  },
  {
    name: "습팸",
    color: "#3498db",
    members: [
      { id: "hwt1014",        name: "가습기",   leader: true },
      { id: "o0opha",         name: "서라0" },
      { id: "irrilll",        name: "이릴" },
      { id: "janine95kim",    name: "재닌" },
      { id: "tndk321",        name: "단수아" },
      { id: "gkxl1004",       name: "하티하티" },
      { id: "pinkmold0317",   name: "강분팡" },
      { id: "ekrekrnfl9",     name: "야뿌" },
      { id: "ju010228",       name: "쥬멩이" },
      { id: "manlebreadtv",   name: "습늘빵" },
      { id: "odoeun",         name: "쨈도은" },
      { id: "khj011219",      name: "기찬하" },
    ],
  },
  {
    name: "꾸한성",
    color: "#9b59b6",
    members: [
      { id: "aksen7833",      name: "꾸티뉴",   leader: true },
      { id: "northpole",      name: "엔쥬" },
      { id: "dbsk0708",       name: "딴딴2당" },
      { id: "not15987",       name: "다뮤" },
      { id: "top6373",        name: "란다" },
      { id: "land4968",       name: "야무지" },
      { id: "wooyah21",       name: "바먀" },
      { id: "sellkey",        name: "셀키" },
      { id: "whiteone325",    name: "난워니" },
      { id: "lika07",         name: "리카" },
      { id: "y0unggam",       name: "영감" },
      { id: "suupercutie",    name: "초귀요미" },
    ],
  },
  {
    name: "그린캠프",
    color: "#27ae60",
    members: [
      { id: "hrlim95",        name: "로기다",   leader: true },
      { id: "secymyong",      name: "묭씨" },
      { id: "cosmicaaarrr",   name: "아르르" },
      { id: "e9dongsung",     name: "추멘" },
      { id: "imhanbily",      name: "한비" },
      { id: "oneon1y",        name: "온유일" },
      { id: "miome3",         name: "고미호" },
      { id: "eunchr",         name: "은초롱" },
      { id: "phs6162",        name: "찐랑" },
      { id: "mnomno55",       name: "루디딕" },
      { id: "sakbi1",         name: "삭비" },
      { id: "yotsubakoe",     name: "코에" },
    ],
  },
  {
    name: "털즈란",
    color: "#e67e22",
    members: [
      { id: "jaeparkk",       name: "박재박",   leader: true },
      { id: "tdnlamuron",     name: "다시바" },
      { id: "morgan427",      name: "숙희" },
      { id: "hhr001234",      name: "어쩜냥이" },
      { id: "ksue336",        name: "슈니" },
      { id: "jo0ju492",       name: "에망" },
      { id: "yeyo25",         name: "예요예요" },
      { id: "nslah830",       name: "피치" },
      { id: "hongkillsoon",   name: "홍길순" },
      { id: "ballty0719",     name: "공태연" },
      { id: "naye0418",       name: "나예" },
      { id: "leesoi34",       name: "냥쏘" },
    ],
  },
];

module.exports = { CREW_LIST };
