const BJ_LIST = {
  y1026            : { name: "철구형2↑" },
  devil0108        : { name: "감스트" },
  lshooooo         : { name: "이상호" },
  khm11903         : { name: "봉준" },
  wnnw             : { name: "남순" },
  rrvv17           : { name: "항상#킴성태" },
  jdm1197          : { name: "악어∀" },
  galsa            : { name: "두치와뿌꾸" },
  phonics1         : { name: "김민교." },
  nila25           : { name: "유소나" },
  aflol            : { name: "LCK_KR" },
  zkwks4413        : { name: "꿀탱탱" },
  yuambo           : { name: "A-염보성!!" },
  ecvhao           : { name: "우왁굳" },
  b13246           : { name: "타요*" },
  gyeonjahee       : { name: "견자희" },
  lyj9306          : { name: "사과몽" },
  "1004suna"       : { name: "임아니" },
  pookygamja       : { name: "[BJ]김인호" },
  gosegu2          : { name: "고세구!" },
  eunyoung1238     : { name: "그릴래영" },
  sky2713          : { name: "나는상윤" },
  lovely5959       : { name: "수피" },
  lilpa0309        : { name: "릴파♬" },
  arinbbidol       : { name: "기뉴다" },
  townboy          : { name: "스맵임" },
  jingburger1      : { name: "징버거☆" },
  viichan6         : { name: "비챤" },
  cotton1217       : { name: "주르르" },
  rkdakstlr911     : { name: "강만식" },
  tntntn13         : { name: "안녕수야" },
  ioioiobb         : { name: "정윤종.." },
  kiss281004       : { name: "피넛ㅁ" },
  rud9281          : { name: "한갱" },
  pyh3646          : { name: "박진우[JINU]" },
  rlatldgus        : { name: "오메킴승현2" },
  wnstn0905        : { name: "(주)박사장$" },
  under444         : { name: "주보리♥" },
  dkrn56           : { name: "˚다누리" },
  smmms2002        : { name: "러아♡" },
  nanajam          : { name: "우정잉" },
  wodnrdldia       : { name: "Best도재욱" },
  gks2wl           : { name: "앵지" },
  e9dongsung       : { name: "이스타추멘!" },
  lolsos           : { name: "#미래:3" },
  gudcjf604        : { name: "블랙워크" },
  hockey05         : { name: "#필메" },
  hyn8210          : { name: "토끼예나" },
  siiyeon          : { name: "애교용" },
  apple1004l       : { name: "향이+ㅁ+♥" },
  xoals137         : { name: "클리드1" },
  mj0128           : { name: "백하♥" },
  jrdart           : { name: "이지상:)" },
  "595935"         : { name: "상어녀" },
  sdkels           : { name: "강덕구" },
  poos69           : { name: "트할_" },
  suhee0051        : { name: "수힛" },
  gksdidqksxn      : { name: "준밧드" },
  daybymin         : { name: "마이민♡" },
  legendhyuk       : { name: "오아" },
  gkdlqk13         : { name: "칸_김동하" },
  thwl9386         : { name: "지붕위소희" },
  cnsgkcnehd74     : { name: "Alo.조경훈" },
  tjrdbs999        : { name: "지피티" },
  he0901           : { name: "해기_" },
  nmangoquince     : { name: "망구랑" },
  vf3366           : { name: "“클로이”" },
  rmlrl771         : { name: "끠끼" },
  "243000"         : { name: "천양" },
  jey422           : { name: "뢴트게늄" },
  roket0829        : { name: "[JS]박퍼니" },
  bhw2209          : { name: "나는푸르" },
  mygomiee         : { name: "마이곰이_" },
  iamquaddurup     : { name: "장지수" },
  dlsn9911         : { name: "제갈금자" },
  ogm0905          : { name: "오뀨!" },
  pubg             : { name: "PUBG공식" },
  kaksjak0730      : { name: "한결___" },
  tleod1818        : { name: "빙밍_" },
  yeopuu           : { name: "여푸" },
  kimdoenmo        : { name: "김된모!" },
  aksen7833        : { name: "꾸티뉴" },
  toryvac          : { name: "빅토리~!" },
  madaomm          : { name: "마다옴_" },
  danchu17         : { name: "단츄♪" },
  mingyeolhee      : { name: "민결희" },
  y970308          : { name: "루루♥" },
  tmdgus5411       : { name: "Ria_리아" },
  qls930205        : { name: "핀아PinA" },
  maoruyakr        : { name: "마왕루야" },
  deathhammer      : { name: "데스해머쵸로" },
  busky3           : { name: "하두링" },
  qkfhzhals        : { name: "EscA_에스카" },
  owozzz           : { name: "샤르망" },
  sirianrain       : { name: "시리안_레인" },
  na2un            : { name: "박나닝" },
  qweasd3456       : { name: "바밍_" },
  ramzzang         : { name: "기래민" },
  chlrlaud1        : { name: "최기명" },
  aa6232           : { name: "쥐돌이쥐돌이" },
  yjw5067          : { name: "봄세이" },
  mawang0216       : { name: "마왕0216" },
  beadyo97         : { name: "구슬요" },
  yeorumi030       : { name: "여르미_" },
  nigttp12         : { name: "뿌리." },
  yoonesaem        : { name: "윤이샘" },
  liloolil         : { name: "해솔♡" },
  insome0319       : { name: "따린" },
  larothy          : { name: "라로시_" },
  yangdoki         : { name: "양도끼" },
  nangnan          : { name: "깐숙" },
  sl0724           : { name: "성기사샬롯" },
  afbaseball1      : { name: "야구중립1" },
  kymakyma         : { name: "키마" },
  beemong          : { name: "비몽♪" },
  pushpull2027     : { name: "이라333" },
  gofl2237         : { name: "해리" },
  hwt1014          : { name: "가습기" },
  blackchu         : { name: "난초." },
  chaenna02        : { name: "챈나" },
  clzhf123         : { name: "우질" },
  kyoonah1217      : { name: "♡소유나♡" },
  qn308dud         : { name: "한둬얼" },
  danz59           : { name: "단즈_" },
  duvl123          : { name: "모요" },
  caramel007       : { name: "_카라멜" },
  song1218         : { name: "하이요" },
  yukki62          : { name: "♡유키♡" },
  kus03125         : { name: "뀨알" },
  bach023          : { name: "울산큰고래" },
  eugenebaduk      : { name: "대머리도적" },
  kmj05317         : { name: "우리밍_" },
  ksh7637          : { name: "BJ공파리파" },
  jaeparkk         : { name: "사내.박재박" },
  lhtlgm           : { name: "홍타쿠!" },
  dobby1031        : { name: "도현ツ" },
  kgoyangyeeee     : { name: "누눙지" },
  cjstkdbsl3       : { name: "깡담비" },
  gine7777         : { name: "킥갓♥" },
  gjstn7637        : { name: "아뚱." },
  singgyul         : { name: "띵귤_" },
  dksldi1010       : { name: "추르미" },
  yeveee           : { name: "유설아♡" },
  cctvno           : { name: "유연서" },
  xodud1898        : { name: "태영♥" },
  dkfka8945        : { name: "〃라미〃" },
  cownsgur123      : { name: "버니버니_" },
  chunbongtv       : { name: "춘봉_" },
  rose0957         : { name: "한세긴" },
  "9mogu9"         : { name: "모구구" },
  qooqoo3110       : { name: "쿠우♪" },
  doormomo         : { name: "문모모" },
  htvv2i           : { name: "햇비" },
  whatcherry4      : { name: "연초록♪" },
  dlswldus107      : { name: "인지연JYEON" },
  sikhye1004       : { name: "거대별" },
  kyaang123        : { name: "캬앙" },
  bboringirl       : { name: "뽀린걸" },
  nanamoon777      : { name: "나나문" },
  s07o24           : { name: "송밤" },
  kisss2           : { name: "김야미♥" },
  hiyoko040        : { name: "히요코" },
  hichume          : { name: "히츠메" },
  gosummer         : { name: "고여름_" },
  jaesu111         : { name: "재수피기" },
  cococ11          : { name: "코코양" },
  hrlim95          : { name: "로기다" },
  muse0116         : { name: "뮤즈_MUSE" },
  evacc7391        : { name: "일하는용형" },
  hyundana         : { name: "현단아v" },
  rhakdncjs90      : { name: "으냉이" },
  "2ducksoo"       : { name: "이덕수할아바" },
  afsoccer1        : { name: "축구중립1" },
  "17282486"       : { name: "하나나" },
  gilming22        : { name: "순녀♥" },
  kirababy2        : { name: "유키라" },
  dnwnwjdqhr53     : { name: "설레랑" },
  wjdfogur98       : { name: "대월향" },
  jungtur          : { name: "융터르" },
  mocamu2          : { name: "모카:b" },
  dalta20          : { name: "달타!" },
  mini8282         : { name: "(설이)" },
  kto9472          : { name: "옥맨" },
  sie4yu           : { name: "유시에" },
  guqlswls123      : { name: "따스히" },
  navixx           : { name: "나비" },
  mmange2          : { name: "망개♪" },
  wellro314        : { name: "김웰로" },
  beyou0728        : { name: "피유." },
  chachki          : { name: "차쯔키" },
  jangjh5409       : { name: "진호." },
  gio12025         : { name: "류채아" },
  toocat030        : { name: "또오냥♥" },
  soyoung6056      : { name: "빡쏘" },
  chamingcha       : { name: "차밍챠" },
  os3n0o           : { name: "김세노" },
  whiteone325      : { name: "난워니-_-+" },
  k0roshi          : { name: "시로코♬" },
  sunglim001       : { name: "떵규_" },
  doodong          : { name: "냥냥두둥" },
  zzonii           : { name: "한쪼니" },
  atl              : { name: "STL공식" },
  nunknown314      : { name: "미현영♡" },
  nmohoho          : { name: "달묘_" },
  llangkko0429     : { name: "랑코_" },
  hachi97          : { name: "하치_HACHI" },
  dlaalswl22       : { name: "임밍지" },
  shandyhan        : { name: "섄디한" },
  uouoas12g        : { name: "정현서비" },
  sircharlee       : { name: "찰리씨" },
  luckycontrol     : { name: "고속도로호준" },
  harumyong        : { name: "하루묭." },
  shb0910          : { name: "아이코_" },
  lunavely4        : { name: "설레나♥" },
  lomioeov         : { name: "치치º^º" },
  wjswpalssla1     : { name: "전제민" },
  naong2bbang      : { name: "나옹이빵" },
  et0726           : { name: "꼼모리" },
  freecslol        : { name: "수퍼스LoL" },
  wja06041         : { name: "해나땅" },
  dalchesom        : { name: "달체솜" },
  cocomizzang      : { name: "코코미짱" },
  tus7475          : { name: "김주디." },
  land4968         : { name: "야무지♪" },
  piano4319        : { name: "쏘야♥" },
  nerdult          : { name: "너덜트유현규" },
  qzaads1          : { name: "나솜" },
  libre1900        : { name: "리브레ㆍ" },
  kwonjiin1215     : { name: "권지인입니다" },
  iop2554          : { name: "바밤바*" },
  chuchan          : { name: "츄쨩_" },
  foxyeon          : { name: "여우연" },
  ddikku0714       : { name: "띠꾸♥" },
  hellofreecup     : { name: "신입SOOP" },
  qkrdnxozz        : { name: "우태" },
  scan1014         : { name: "Scan유승곤" },
  dduduji          : { name: "두두지!" },
  ddalgishoux      : { name: "망고슈몽이" },
  ginko001125      : { name: "198번" },
  afmusician       : { name: "음악SOOP" },
  kaam0802         : { name: "카아암" },
  roundpopo        : { name: "땡글땡글포포" },
  tsukizz6         : { name: "움츠키" },
  wjdekgus112      : { name: "정다니" },
  min030606        : { name: "면추가♥" },
  cherru           : { name: "최애리" },
  kkyubog          : { name: "뀨복" },
  ododk729         : { name: "수붕e" },
  kespa            : { name: "KeSPA공식" },
  kakazzang        : { name: "후룽카카" },
  wkdghdtjr99      : { name: "여백이다" },
  godnjs8482       : { name: "박해원:)" },
  lighthoong       : { name: "설홍" },
  seasonal         : { name: "콘텐츠SOOP" },
  ducke77          : { name: "밀크티냠" },
  thswlstjr666     : { name: "손진석." },
  peperopero55     : { name: "나노×" },
  kkeuna           : { name: "강은아" },
  duddj4210        : { name: "뚜우♡" },
  happyness192     : { name: "김뱅글:Þ" },
  siioyeyo         : { name: "시오∋" },
  dalnim419        : { name: "히마리♥" },
  padott           : { name: "페닷" },
  xirus2           : { name: "시루냥" },
  mukbangbj        : { name: "먹쿡SOOP" },
  harxxxne         : { name: "하루네♪" },
  afmma            : { name: "격투기중립" },
  usermeeting      : { name: "숲유저간담회" },
  uoip209          : { name: "미요♭" },
  aniplustv        : { name: "aniplustv" },
  nnojoke486       : { name: "짱난하나" },
  baky1996         : { name: "【나리♥】" },
  riphin0511       : { name: "리핀♥" },
  afreporter       : { name: "SOOP프레스" },
  b4bycthu1hu      : { name: "데로DERO" },
  "100noru"        : { name: "백노루" },
  ruki7            : { name: "oo하데스oo" },
  rlaalstnsd       : { name: "김봉준" },
  dbstpwls97       : { name: "라핀드래곤" },
  imyourr          : { name: "깅두부" },
  skylovezzz1      : { name: "남티여티()" },
  js1123456        : { name: "Rx여우비_" },
  hsj3146          : { name: ".프레이" },
  zotnlqkfmwk      : { name: ".학살" },
  cyzhquf          : { name: "리냐" },
  dnjfem4809       : { name: "미스틱.." },
  ksyjh1687        : { name: "밍턴" },
  blueastom        : { name: "문월" },
  jsjdjdjsj        : { name: "온네임" },
  djbhc7           : { name: "김하랑" },
  djbhc6           : { name: "오메킴" },
  ambler           : { name: "쉬바" },
  thekaran         : { name: "맛지" },
  hoinida          : { name: "꽃봉오리3" },
  anddy1234583     : { name: "오연하" },
  alstlr1245       : { name: "투냥츠" },
  dodldoidi        : { name: "떙지+" },
  idlovehina       : { name: "김쿼카" },
  saturn512        : { name: "망야" },
  ollehbk          : { name: "빕어" },
  puma2255         : { name: "이세돌" },
  je7857           : { name: "아이쨩" },
  dionzzz          : { name: "하루비" },
  forevermiri1     : { name: "철권무릎" },
  onnmin363        : { name: "결망전분석가" },
  dadada           : { name: "dadada(1)" },
  leotelp          : { name: "하랑E" },
  dowon0610        : { name: "딮기" },
  kyunas5          : { name: "윤하랑" },
  nthkim3022       : { name: "더빙레이디" },
  drdopamine       : { name: "도파민박사" },
  soria5           : { name: "김나오" },
  neunho29         : { name: "황태영" },
  "20000song"      : { name: "백만송♥" },
  kd0011           : { name: "GenGEsports" },
  inehine          : { name: "아이네♪" },
  xx00uxx          : { name: "윤하랑=_=" },
  joey1114         : { name: "저라뎃" },
  candyrang00      : { name: "하랑e♥" },
  son4069          : { name: "빵지니♥" },
  dkwkal           : { name: "탱크~_~" },
  rlaxordyd        : { name: "Bisu김택용" },
  byflash          : { name: "FlaSh.이영호" },
  rlekfu6          : { name: "박재혁;;;" },
  jk890202         : { name: "JuM.윤중2" },
  dbsdydx          : { name: "free윤용태" },
  mwhdgus          : { name: "윤진규" },
  jmc06170         : { name: "왜냐맨장민철" },
  byromantic       : { name: "최재성:)" },
  kuyol            : { name: "910★강구열" },
  yjk011599        : { name: "나무늘봉순" },
  vlfvlf789        : { name: "빵훈이" },
  tjgpdus97        : { name: "요닝♡." },
  qpqpro           : { name: "디임" },
  zalalz           : { name: "오조은" },
  yochba0402       : { name: "졈니" },
  rhf104           : { name: "란란_" },
  mew030709        : { name: "남수댕" },
  moguleave        : { name: "모리_" },
  ouo20411         : { name: "히댕" },
  imducko3o        : { name: "오리꿍" },
  queen030         : { name: "효짱♥" },
  dlwldyal1004     : { name: "이지다" },
  eunjo0105        : { name: "은조:E" },
};

const POPULAR_BJ_IDS = [
  "y1026",      // 철구
  "devil0108",  // 감스트
  "khm11903",   // 봉준
  "phonics1",   // 김민교
  "rrvv17",     // 킴성태
  "yuambo",     // 염보성
  "lshooooo",   // 이상호
  "wnnw",       // 남순
  "joey1114",   // 저라뎃
];

// 애청자 수 내림차순 (JS 객체는 숫자 키를 앞으로 정렬하므로 별도 배열 필요)
const BJ_ORDER = [
  "y1026","devil0108","lshooooo","khm11903","wnnw","rrvv17","jdm1197","galsa",
  "phonics1","nila25","aflol","zkwks4413","yuambo","ecvhao","b13246","gyeonjahee",
  "lyj9306","1004suna","pookygamja","gosegu2","eunyoung1238","sky2713","lovely5959",
  "lilpa0309","arinbbidol","townboy","jingburger1","viichan6","cotton1217","rkdakstlr911",
  "tntntn13","ioioiobb","kiss281004","rud9281","pyh3646","rlatldgus","wnstn0905",
  "under444","dkrn56","smmms2002","nanajam","wodnrdldia","gks2wl","e9dongsung",
  "lolsos","gudcjf604","hockey05","hyn8210","siiyeon","apple1004l","xoals137",
  "mj0128","jrdart","595935","sdkels","poos69","suhee0051","gksdidqksxn","daybymin",
  "legendhyuk","gkdlqk13","thwl9386","cnsgkcnehd74","tjrdbs999","he0901","nmangoquince",
  "vf3366","rmlrl771","243000","jey422","roket0829","bhw2209","mygomiee","iamquaddurup",
  "dlsn9911","ogm0905","pubg","kaksjak0730","tleod1818","yeopuu","kimdoenmo","aksen7833",
  "toryvac","madaomm","danchu17","mingyeolhee","y970308","tmdgus5411","qls930205",
  "maoruyakr","deathhammer","busky3","qkfhzhals","owozzz","sirianrain","na2un",
  "qweasd3456","ramzzang","chlrlaud1","aa6232","yjw5067","mawang0216","beadyo97",
  "yeorumi030","nigttp12","yoonesaem","liloolil","insome0319","larothy","yangdoki",
  "nangnan","sl0724","afbaseball1","kymakyma","beemong","pushpull2027","gofl2237",
  "hwt1014","blackchu","chaenna02","clzhf123","kyoonah1217","qn308dud","danz59",
  "duvl123","caramel007","song1218","yukki62","kus03125","bach023","eugenebaduk",
  "kmj05317","ksh7637","jaeparkk","lhtlgm","dobby1031","kgoyangyeeee","cjstkdbsl3",
  "gine7777","gjstn7637","singgyul","dksldi1010","yeveee","cctvno","xodud1898",
  "dkfka8945","cownsgur123","chunbongtv","rose0957","9mogu9","qooqoo3110","doormomo",
  "htvv2i","whatcherry4","dlswldus107","sikhye1004","kyaang123","bboringirl","nanamoon777",
  "s07o24","kisss2","hiyoko040","hichume","gosummer","jaesu111","cococ11","hrlim95",
  "muse0116","evacc7391","hyundana","rhakdncjs90","2ducksoo","afsoccer1","17282486",
  "gilming22","kirababy2","dnwnwjdqhr53","wjdfogur98","jungtur","mocamu2","dalta20",
  "mini8282","kto9472","sie4yu","guqlswls123","navixx","mmange2","wellro314","beyou0728",
  "chachki","jangjh5409","gio12025","toocat030","soyoung6056","chamingcha","os3n0o",
  "whiteone325","k0roshi","sunglim001","doodong","zzonii","atl","nunknown314","nmohoho",
  "llangkko0429","hachi97","dlaalswl22","shandyhan","uouoas12g","sircharlee","luckycontrol",
  "harumyong","shb0910","lunavely4","lomioeov","wjswpalssla1","naong2bbang","et0726",
  "freecslol","wja06041","dalchesom","cocomizzang","tus7475","land4968","piano4319",
  "nerdult","qzaads1","libre1900","kwonjiin1215","iop2554","chuchan","foxyeon",
  "ddikku0714","hellofreecup","qkrdnxozz","scan1014","dduduji","ddalgishoux","ginko001125",
  "afmusician","kaam0802","roundpopo","tsukizz6","wjdekgus112","min030606","cherru",
  "kkyubog","ododk729","kespa","kakazzang","wkdghdtjr99","godnjs8482","lighthoong",
  "seasonal","ducke77","thswlstjr666","peperopero55","kkeuna","duddj4210","happyness192",
  "siioyeyo","dalnim419","padott","xirus2","mukbangbj","harxxxne","afmma","usermeeting",
  "uoip209","aniplustv","nnojoke486","baky1996","riphin0511","afreporter","b4bycthu1hu",
  "100noru","ruki7","rlaalstnsd","dbstpwls97","imyourr","skylovezzz1","js1123456",
  "hsj3146","zotnlqkfmwk","cyzhquf","dnjfem4809","ksyjh1687","blueastom","jsjdjdjsj",
  "djbhc7","djbhc6","ambler","thekaran","hoinida","anddy1234583","alstlr1245","dodldoidi",
  "idlovehina","saturn512","ollehbk","puma2255","je7857","dionzzz","forevermiri1",
  "onnmin363","dadada","leotelp","dowon0610","kyunas5","nthkim3022","drdopamine",
  "soria5","neunho29","20000song","kd0011",
  "inehine","xx00uxx","joey1114","candyrang00","son4069","dkwkal",
  "rlaxordyd","byflash","rlekfu6","jk890202","dbsdydx","mwhdgus","jmc06170","byromantic",
  "kuyol","yjk011599","vlfvlf789","tjgpdus97","qpqpro","zalalz","yochba0402",
  "rhf104","mew030709","moguleave","ouo20411","imducko3o","queen030","dlwldyal1004","eunjo0105",
];

module.exports = { BJ_LIST, BJ_ORDER, POPULAR_BJ_IDS };
